name: BZN_Released_Managment_Workflow-Email

on:
  push:
    branches:
      - master
    paths:
      - 'Released/**'

jobs:
  send-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install 7-Zip & Node.js
        run: |
          sudo apt-get update && sudo apt-get install -y p7zip-full
          npm init -y
          npm install nodemailer

      - name: Get today's date
        run: echo "TODAY_DATE=$(date +%F)" >> $GITHUB_ENV

      - name: Find all files in 'Released/' folder with current date
        id: dated_files
        run: |        
          MATCHED_FILES=$(find Released/ -type f -name "*$TODAY_DATE*" -printf "%T@ %p\n" \
              | sort -n | tail -1 | cut -d' ' -f2-)

          
          if [ -z "$MATCHED_FILES" ]; then
            echo "No files found with today's date: $TODAY_DATE"
            exit 1
          fi
          echo "$MATCHED_FILES" > matched_files.txt
          echo "HAS_MATCHED_FILES=true" >> $GITHUB_ENV

      - name: Zip all matched files
        if: env.HAS_MATCHED_FILES == 'true'
        run: |
          FILE_ARGS=""
          while IFS= read -r line; do
            FILE_ARGS+=" \"$line\""
          done < matched_files.txt
          eval "7z a -tzip -p${{ secrets.ZIP_PASSWORD }} -mem=ZipCrypto New_Released.zip $FILE_ARGS"

      - name: Send email via nodemailer
        if: env.HAS_MATCHED_FILES == 'true'
        env:
          SMTP_SERVER: smtp.rediffmailpro.com
          SMTP_PORT: 465
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          EMAIL_CC: ${{ secrets.EMAIL_CC }}
          EMAIL_SUBJECT: "Byzan Systems Release for ${{ env.TODAY_DATE }}"
          EMAIL_BODY: |
            Hello,
            Attached is the password-protected zip file containing all release files from the 'Released' folder for today's date.
            Please use the shared password to extract its contents.
            Note: This is an automated email, please do not reply.
            Regards,  
            Byzan Release Management
          HELO_HOST: rediffmailpro.com
          IGNORE_CERT: true
        run: node BZN_Send_Email.js
